server:
  port: 9527

spring:
  application:
    name: "mybatis-plus-navigator-test"
  profiles:
    active: dev

mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    call-setters-on-nulls:
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID

logging:
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'